language: node_js
node_js:
  - '12'
git:
  depth: false

before_script:
  - git fetch origin master
  - yarn install

script:
  - npm run affected:build -- --base=origin/master --parallel
  - npm run affected:test -- --all --code-coverage --skip-nx-cache
  - npm run affected:lint -- --base=origin/master --parallel
  - npm run e2e --headless
  - npm run format
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

cache:
  directories:
    - 'node_modules'

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/*
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true

addons:
  sonarcloud:
    organization: 'naetverkjs'
    token: $SONAR_TOKEN
